# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        stages: [push]
    -   id: end-of-file-fixer
        stages: [push]
    -   id: check-yaml
        stages: [push]
    -   id: check-added-large-files
        stages: [push]
    -   id: detect-private-key
        stages: [push]
    -   id: name-tests-test
        stages: [push]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
        stages: [push]
    -   id: ruff-format
        stages: [push]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        stages: [push]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        stages: [push]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        stages: [push]
